package com.qfedu.pojo;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.aid
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.aname
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acount
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    private Integer acount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.amoney
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    private Integer amoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.aispay
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    private Byte aispay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.apname
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    private String apname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ainfo
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    private String ainfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.atime
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    private Long atime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.aid
     *
     * @return the value of account.aid
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.aid
     *
     * @param aid the value for account.aid
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.aname
     *
     * @return the value of account.aname
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.aname
     *
     * @param aname the value for account.aname
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acount
     *
     * @return the value of account.acount
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public Integer getAcount() {
        return acount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acount
     *
     * @param acount the value for account.acount
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public void setAcount(Integer acount) {
        this.acount = acount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.amoney
     *
     * @return the value of account.amoney
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public Integer getAmoney() {
        return amoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.amoney
     *
     * @param amoney the value for account.amoney
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public void setAmoney(Integer amoney) {
        this.amoney = amoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.aispay
     *
     * @return the value of account.aispay
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public Byte getAispay() {
        return aispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.aispay
     *
     * @param aispay the value for account.aispay
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public void setAispay(Byte aispay) {
        this.aispay = aispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.apname
     *
     * @return the value of account.apname
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public String getApname() {
        return apname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.apname
     *
     * @param apname the value for account.apname
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public void setApname(String apname) {
        this.apname = apname == null ? null : apname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ainfo
     *
     * @return the value of account.ainfo
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public String getAinfo() {
        return ainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ainfo
     *
     * @param ainfo the value for account.ainfo
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public void setAinfo(String ainfo) {
        this.ainfo = ainfo == null ? null : ainfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.atime
     *
     * @return the value of account.atime
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public Long getAtime() {
        return atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.atime
     *
     * @param atime the value for account.atime
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    public void setAtime(Long atime) {
        this.atime = atime;
    }

	@Override
	public String toString() {
		return "Account [aid=" + aid + ", aname=" + aname + ", acount=" + acount + ", amoney=" + amoney + ", aispay="
				+ aispay + ", apname=" + apname + ", ainfo=" + ainfo + ", atime=" + atime + "]";
	}
    
}