package com.qfedu.pojo;

public class Provider {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column providers.pid
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column providers.pname
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column providers.pdecription
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    private String pdecription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column providers.plinkman
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    private String plinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column providers.ptel
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    private String ptel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column providers.paddress
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    private String paddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column providers.pid
     *
     * @return the value of providers.pid
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column providers.pid
     *
     * @param pid the value for providers.pid
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column providers.pname
     *
     * @return the value of providers.pname
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column providers.pname
     *
     * @param pname the value for providers.pname
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column providers.pdecription
     *
     * @return the value of providers.pdecription
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public String getPdecription() {
        return pdecription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column providers.pdecription
     *
     * @param pdecription the value for providers.pdecription
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public void setPdecription(String pdecription) {
        this.pdecription = pdecription == null ? null : pdecription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column providers.plinkman
     *
     * @return the value of providers.plinkman
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public String getPlinkman() {
        return plinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column providers.plinkman
     *
     * @param plinkman the value for providers.plinkman
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public void setPlinkman(String plinkman) {
        this.plinkman = plinkman == null ? null : plinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column providers.ptel
     *
     * @return the value of providers.ptel
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public String getPtel() {
        return ptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column providers.ptel
     *
     * @param ptel the value for providers.ptel
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public void setPtel(String ptel) {
        this.ptel = ptel == null ? null : ptel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column providers.paddress
     *
     * @return the value of providers.paddress
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public String getPaddress() {
        return paddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column providers.paddress
     *
     * @param paddress the value for providers.paddress
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    public void setPaddress(String paddress) {
        this.paddress = paddress == null ? null : paddress.trim();
    }
}