package com.qfedu.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.qfedu.pojo.Account;
@Repository
public interface AccountMapper {
	int insertAccount(Account account);
	List<Account> selectAccountlist();
	List<Account> selectAccount(Account account);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    int deleteByPrimaryKey(Account account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    Account selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Fri Nov 03 20:17:38 CST 2017
     */
    int updateByPrimaryKey(Account record);
}