package com.qfedu.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.qfedu.pojo.Provider;
@Repository
public interface ProviderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    int insert(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    int insertSelective(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    Provider selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    int updateByPrimaryKeySelective(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Thu Nov 02 20:22:50 CST 2017
     */
    int updateByPrimaryKey(Provider record);
    List<Provider> seleteAllProvider();
    int deleteProvider(Provider provider);
    List<Provider> searchProvider(Provider provider);
    List<Provider> seleteProviderByName(Provider provider);
    int insertName(Provider provider);
}